<?php declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20240208154512 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add person, address and person_contact tables.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE address (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, city VARCHAR(255) NOT NULL, postcode VARCHAR(255) NOT NULL, street VARCHAR(255) NOT NULL, person_id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_D4E6F81217BBB47 ON address (person_id)');
        $this->addSql('CREATE TABLE person (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, age SMALLINT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE person_contact (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(255) NOT NULL, value VARCHAR(255) NOT NULL, person_id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_6EFC55B1217BBB47 ON person_contact (person_id)');
        $this->addSql('ALTER TABLE address ADD CONSTRAINT FK_D4E6F81217BBB47 FOREIGN KEY (person_id) REFERENCES person (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE person_contact ADD CONSTRAINT FK_6EFC55B1217BBB47 FOREIGN KEY (person_id) REFERENCES person (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE address DROP CONSTRAINT FK_D4E6F81217BBB47');
        $this->addSql('ALTER TABLE person_contact DROP CONSTRAINT FK_6EFC55B1217BBB47');
        $this->addSql('DROP TABLE address');
        $this->addSql('DROP TABLE person');
        $this->addSql('DROP TABLE person_contact');
    }
}
